#include "map.h"
//sf::String TileMap[HEIGHT_MAP] = {
//	"r--------------------------------------7",
//	"i               wwwww    cc            i",
//	"i      s         wwwwws                i",
//	"i               wwwwwss       s        i",
//	"i    s           wwwws                 i",
//	"i               wwww       c           i",
//	"i             wwwww                    i",
//	"i             swwww                    i",
//	"i             sswwww                   i",
//	"i               wwww                   i",
//	"i  s             www                   i",
//	"i              wwwwww                  i",
//	"i               wwwww       s          i",
//	"i               pppp                   i",
//	"i    s          pppp                   i",
//	"i              wwwww                   i",
//	"i                www                   i",
//	"i                www                   i",
//	"i               wwwww                  i",
//	"i                 wwww                 i",
//	"i     s         wwwwww       h         i",
//	"i                wwwww                 i",
//	"i                 wwww                 i",
//	"i                wwwww                 i",
//	"i                 wwww                 i",
//	"i                 swwwww               i",
//	"i        s        wwwww                i",
//	"i                  wwww                i",
//	"i   h               wwww               i",
//	"L--------------------------------------J",
//};
sf::String TileMap[HEIGHT_MAP] = {
	"r--------------------------------------7",
	"i                        cc            i",
	"i                                      i",
	"i                                      i",
	"i                                      i",
	"i                          c           i",
	"i                                      i",
	"i                                      i",
	"i                                      i",
	"i                                      i",
	"i                                      i",
	"i                                      i",
	"i                                      i",
	"i                                      i",
	"i                                      i",
	"i                                      i",
	"i                                      i",
	"i                                      i",
	"i                                      i",
	"i                                      i",
	"i                            h         i",
	"i                                      i",
	"i                                      i",
	"i                                      i",
	"i                                      i",
	"i                                      i",
	"i                                      i",
	"i                                      i",
	"i   h                                  i",
	"L--------------------------------------J",
};