#include <SFML\Graphics.hpp>
const int HEIGHT_MAP = 30;//размер карты высота
const int WIDTH_MAP = 40;//размер карты ширина 

sf::String TileMap[HEIGHT_MAP] = {
"r--------------------------------------7",
"i               wwwww                  i",
"i      s         wwwwws                i",
"i               wwwwwss       s        i",
"i    s           wwwws                 i",
"i               wwww                   i",
"i             wwwww                    i",
"i             swwww                    i",
"i             sswwww                   i",
"i               wwww                   i",
"i  s             www                   i",
"i              wwwwww                  i",
"i               wwwww       s          i",
"i               pppp                   i",
"i    s          pppp                   i",
"i              wwwww                   i",
"i                www                   i",
"i                www                   i",
"i               wwwww                  i",
"i                 wwww                 i",
"i     s         wwwwww                 i",
"i                wwwww                 i",
"i                 wwww                 i",
"i                wwwww                 i",
"i                 wwww                 i",
"i                 swwwww               i",
"i        s        wwwww                i",
"i                  wwww                i",
"i                   wwww               i",
"L--------------------------------------J",
};
